### ISSUE TITLE
Package does not work in Sublime Text 2.0.2 Build 2221 on OS X

### ISSUE THREAD

**Issue by ghost** [matthew-dumas/syntax_definition_helper#1]
Dear Matthew,

Today, I installed your Syntax Definition Helper package for Sublime Text 2. Unfortunately it is not working. The package is listed as installed but the commands for creating and editing syntax definitions (ALT-CTRL-6 / ALT-CTRL-7 ) are not working. They are not listed in the command palette.

I am on Mac OS X (10.8.5) and Sublime Text 2.0.2 Build 2221.

Is the issue that there is only a keymap file for Windows? If this is the problem how do I have to call such a file for OS X? If this is not the problem where else or what else should I cheek?

Best,
Helge

**Comment by matthew-dumas** [comment]
Good evening, Helge, 

I just uploaded keymaps for Linux and OSX. As I do not currently run either of those systems, I can't verify that these keymaps are working. Please let me know if the OSX keymap works.

-M

**Comment by ghost** [comment]
Hi Matthew,

Thank you very much for the quick reply and for uploading the new keycap files. Now your package works for me! It is really cool and a time saver.

To make it work completely, I had to change the hard coded backslashes into os.sep calls. If you want to I can commit my changes to the code.

Best,
Helge

**Comment by matthew-dumas** [comment]
Sounds good to me! I look forward to the update.
